use break_infinity::Decimal;

pub(crate) struct GameConstants {
    // interns recruitment cost
    pub interns_loc_base_cost: Decimal,
    pub interns_loc_growth_rate: Decimal,
    // junior devs recruitment cost
    pub junior_devs_loc_base_cost: Decimal,
    pub junior_devs_loc_growth_rate: Decimal,
    // senior devs recruitment cost
    pub senior_devs_loc_base_cost: Decimal,
    pub senior_devs_loc_growth_rate: Decimal,
    // research once costs
    pub research_internship_loc_cost: Decimal,
    pub research_junior_devs_position_loc_cost: Decimal,
    pub research_senior_devs_position_loc_cost: Decimal,
    pub research_interns_promotion_loc_cost: Decimal,
    pub research_junior_devs_promotion_loc_cost: Decimal,
    pub research_code_metrics_loc_cost: Decimal,
    pub research_speedrun_loc_cost: Decimal,
    pub research_logs_loc_cost: Decimal,
    pub research_rmrf_loc_cost: Decimal,
    pub research_toggle_theme_loc_cost: Decimal,
    // initial promotion ratio
    pub interns_promotion_ratio_dt: Decimal,
    pub junior_devs_promotion_ratio_dt: Decimal,
    pub senior_devs_retirement_ratio_dt: Decimal,
    // devs loc production
    pub interns_loc_dt: Decimal,
    pub junior_devs_loc_dt: Decimal,
    pub senior_devs_loc_dt: Decimal,
    // manual loc production
    pub loc_per_clicks: Decimal,
    pub debug_per_clicks: Decimal,
    // bugs ratio
    pub manual_bugs_ratio: Decimal,
    pub interns_bugs_ratio: Decimal,
    pub junior_devs_bugs_ratio: Decimal,
    pub senior_devs_bugs_ratio: Decimal,
    // quests
    pub quest_hello_world_loc_cost: Decimal,
    pub quest_fizz_buzz_loc_cost: Decimal,
    pub quest_calculator_loc_cost: Decimal,
    pub quest_game_of_life_loc_cost: Decimal,
    pub quest_text_editor_loc_cost: Decimal,
    pub quest_physics_engine_loc_cost: Decimal,
    pub quest_bacteria_loc_cost: Decimal,
    pub quest_browser_loc_cost: Decimal,
    pub quest_kernel_loc_cost: Decimal,
    pub quest_mouse_loc_cost: Decimal,
    pub quest_human_brain_loc_cost: Decimal,
    pub quest_economy_loc_cost: Decimal,
    pub quest_climate_loc_cost: Decimal,
    pub quest_earth_loc_cost: Decimal,
    pub quest_solar_system_loc_cost: Decimal,
    pub quest_universe_loc_cost: Decimal,
    pub quest_differentiation_loc_cost: Decimal,
}

impl Default for GameConstants {
    fn default() -> Self {
        GameConstants {
            interns_loc_base_cost: Decimal::new(10.0),
            interns_loc_growth_rate: Decimal::new(1.1),
            junior_devs_loc_base_cost: Decimal::new(20.0),
            junior_devs_loc_growth_rate: Decimal::new(1.1),
            senior_devs_loc_base_cost: Decimal::new(40.0),
            senior_devs_loc_growth_rate: Decimal::new(1.1),
            research_internship_loc_cost: Decimal::new(1.0),
            research_junior_devs_position_loc_cost: Decimal::new(1.0),
            research_senior_devs_position_loc_cost: Decimal::new(1.0),
            research_interns_promotion_loc_cost: Decimal::new(1.0),
            research_junior_devs_promotion_loc_cost: Decimal::new(1.0),
            research_code_metrics_loc_cost: Decimal::new(1.0),
            research_speedrun_loc_cost: Decimal::new(1.0),
            research_logs_loc_cost: Decimal::new(1.0),
            research_rmrf_loc_cost: Decimal::new(1.0),
            research_toggle_theme_loc_cost: Decimal::new(1.0),
            interns_promotion_ratio_dt: Decimal::new(0.04),
            junior_devs_promotion_ratio_dt: Decimal::new(0.02),
            senior_devs_retirement_ratio_dt: Decimal::new(0.01),
            interns_loc_dt: Decimal::new(1.0),
            junior_devs_loc_dt: Decimal::new(1.5),
            senior_devs_loc_dt: Decimal::new(2.0),
            loc_per_clicks: Decimal::new(1.0),
            debug_per_clicks: Decimal::new(1.0),
            manual_bugs_ratio: Decimal::new(1.0),
            interns_bugs_ratio: Decimal::new(2.0),
            junior_devs_bugs_ratio: Decimal::new(1.5),
            senior_devs_bugs_ratio: Decimal::new(1.0),
            quest_hello_world_loc_cost: Decimal::new(1.0),
            quest_fizz_buzz_loc_cost: Decimal::new(10.0),
            quest_calculator_loc_cost: Decimal::new(100.0),
            quest_game_of_life_loc_cost: Decimal::new(1e3),
            quest_text_editor_loc_cost: Decimal::new(1e4),
            quest_physics_engine_loc_cost: Decimal::new(1e5),
            quest_bacteria_loc_cost: Decimal::new(1e6),
            quest_browser_loc_cost: Decimal::new(5e6),
            quest_kernel_loc_cost: Decimal::new(30e6),
            quest_mouse_loc_cost: Decimal::new(100e6),
            quest_human_brain_loc_cost: Decimal::new(1e9),
            quest_economy_loc_cost: Decimal::new(10e9),
            quest_climate_loc_cost: Decimal::new(100e9),
            quest_earth_loc_cost: Decimal::new(1e12),
            quest_solar_system_loc_cost: Decimal::new(1e15),
            quest_universe_loc_cost: Decimal::new(1e18),
            quest_differentiation_loc_cost: Decimal::new(1e21),
        }
    }
}